services:
  note-dev-api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - '3000:3000'
    environment:
      - PORT=3000
      - NODE_ENV=development
    volumes:
      - ./src:/app/src
      - ./node_modules:/app/node_modules
    networks:
      - note-dev
  mysql_db:
    image: mysql
    ports:
      - '3307:3307'
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=note-dev
      - MYSQL_USER=root
      - MYSQL_PASSWORD=password
      - MYSQL_TCP_PORT=3307
    networks:
      - note-dev
networks:
  note-dev:
